# Generated by Django 5.2.10 on 2026-01-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('CONTACT', 'Contact Us'), ('SAMPLE', 'Request Sample'), ('DISCOUNT', 'Ask for Discount'), ('CALLBACK', 'Get a Call Back')], default='CONTACT', max_length=20),
        ),
    ]
