# Generated by Django 5.2.10 on 2026-01-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_lead_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='license_type',
            field=models.CharField(blank=True, choices=[('single', 'Single User'), ('multi', 'Multi User'), ('enterprise', 'Enterprise'), ('data', 'Data Pack')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('CONTACT', 'Contact Us'), ('SAMPLE', 'Request Sample'), ('DISCOUNT', 'Ask for Discount'), ('CALLBACK', 'Get a Call Back'), ('PURCHASE', 'Purchase Report')], default='CONTACT', max_length=20),
        ),
    ]
