# Generated by Django 3.0.6 on 2026-02-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_address_lead_city_lead_license_type_lead_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='country_code',
            field=models.CharField(blank=True, help_text='e.g. +1, +91', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
