# Generated by Django 3.0.6 on 2026-02-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20260205_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
