# Generated by Django 3.0.6 on 2026-02-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20260205_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('CONTACT', 'Contact Us'), ('SAMPLE', 'Request Sample'), ('DISCOUNT', 'Ask for Discount'), ('CALLBACK', 'Get a Call Back'), ('CALLBACK', 'Get a Call Back'), ('PURCHASE', 'Purchase Report'), ('NEWSLETTER', 'Newsletter Subscription')], default='CONTACT', max_length=20),
        ),
    ]
