# Generated by Django 4.2.28 on 2026-02-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_alter_lead_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('CONTACT', 'Contact Us'), ('SAMPLE', 'Request Sample'), ('DISCOUNT', 'Ask for Discount'), ('CUSTOMIZATION', 'Request Customization'), ('CALLBACK', 'Get a Call Back'), ('PURCHASE', 'Purchase Report'), ('NEWSLETTER', 'Newsletter Subscription')], default='CONTACT', max_length=20),
        ),
    ]
