# Generated by Django 5.2.11 on 2026-02-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_page_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Site', max_length=255)),
                ('google_analytics_measurement_id', models.CharField(blank=True, help_text='Example: G-XXXXXXXXXX', max_length=255, null=True)),
                ('google_search_console_verification_code', models.CharField(blank=True, help_text='Example: google-site-verification=XXXXXXXXXX', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
