# Generated by Django 5.2.11 on 2026-02-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_siteconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='google_analytics_measurement_id',
            field=models.CharField(blank=True, help_text='Enter the Measurement ID only (e.g., G-XXXXXXXXXX). If you paste the full script, we will try to extract the ID.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='google_search_console_verification_code',
            field=models.CharField(blank=True, help_text='Enter the verification code or the full meta tag (e.g., google-site-verification=XXXXXXXXXX).', max_length=255, null=True),
        ),
    ]
