# Generated by Django 5.2.11 on 2026-03-16 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcategory_alter_blogpost_publish_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('post_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Blog Import Batches',
                'ordering': ['-import_date'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogimportbatch'),
        ),
    ]
