# Generated by Django 5.2.10 on 2026-01-27 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
                ('sub_category', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(help_text='Report Description/Summary (HTML)')),
                ('toc', models.TextField(help_text='HTML Content', verbose_name='Table of Contents')),
                ('segmentation', models.TextField(help_text='HTML Content')),
                ('methodology', models.TextField(help_text='HTML Content')),
                ('faqs', models.TextField(help_text='JSON or HTML formatted FAQs', verbose_name='FAQs')),
                ('publish_date', models.DateField()),
                ('pages_count', models.IntegerField(default=0)),
                ('base_year', models.CharField(blank=True, max_length=50, null=True)),
                ('forecast_period', models.CharField(blank=True, max_length=100, null=True)),
                ('format_type', models.CharField(default='PDF', max_length=100)),
                ('region', models.CharField(default='Global', max_length=100)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('single_user_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('multi_user_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('enterprise_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_pack_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('sample_url_slug', models.CharField(blank=True, max_length=500, null=True)),
                ('discount_url_slug', models.CharField(blank=True, max_length=500, null=True)),
                ('inquiry_url_slug', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.category')),
            ],
        ),
    ]
