# Generated by Django 3.0.6 on 2026-02-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20260205_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='competitive_environment',
            field=models.TextField(blank=True, help_text='Competitive environment analysis', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='geographic_analysis',
            field=models.TextField(blank=True, help_text='Geographic performance analysis', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='industry_snapshot',
            field=models.TextField(blank=True, help_text='Overview of the industry and market', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='leading_participants',
            field=models.TextField(blank=True, help_text='List of leading market participants', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='long_term_perspective',
            field=models.TextField(blank=True, help_text='Long-term market perspective', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='market_challenges',
            field=models.TextField(blank=True, help_text='Challenges and constraints in the market', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='market_coverage',
            field=models.TextField(blank=True, help_text='Market coverage overview table/content', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='market_growth_catalysts',
            field=models.TextField(blank=True, help_text='Key factors driving market growth', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='report_highlights',
            field=models.TextField(blank=True, help_text='Bullet points highlighting key market insights', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='strategic_opportunities',
            field=models.TextField(blank=True, help_text='Strategic growth opportunities', null=True),
        ),
    ]
