# Generated by Django 5.2.11 on 2026-03-12 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_category_id_alter_report_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('report_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Import Batches',
                'ordering': ['-import_date'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='reports.importbatch'),
        ),
    ]
