# Generated by Django 6.0.3 on 2026-04-06 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_importbatch_report_import_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='author',
        ),
        migrations.RemoveField(
            model_name='report',
            name='competitive_environment',
        ),
        migrations.RemoveField(
            model_name='report',
            name='geographic_analysis',
        ),
        migrations.RemoveField(
            model_name='report',
            name='industry_snapshot',
        ),
        migrations.RemoveField(
            model_name='report',
            name='leading_participants',
        ),
        migrations.RemoveField(
            model_name='report',
            name='long_term_perspective',
        ),
        migrations.RemoveField(
            model_name='report',
            name='market_challenges',
        ),
        migrations.RemoveField(
            model_name='report',
            name='market_coverage',
        ),
        migrations.RemoveField(
            model_name='report',
            name='market_growth_catalysts',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_highlights',
        ),
        migrations.RemoveField(
            model_name='report',
            name='strategic_opportunities',
        ),
        migrations.RemoveField(
            model_name='report',
            name='sub_category',
        ),
    ]
